### ISSUE TITLE
Could not send APDU command

### ISSUE THREAD

**Issue by Innosis** [WisnuAnggoro/simple-apdu-sender#1]
May I know how to send the APDU commands?

**Comment by Labatech** [comment]
Hello Innosis,

I am not the developer of this cool chip card library but here are my commands to send an APDU command:

	    // Initialize Library and get available smart card readers
            SCardWrapper scConnection = new SCardWrapper(SCardScopes.System, SCardShareModes.Shared, SCardProtocol.Any);
            List<string> scReaders = scConnection.GetReaderList();            

            // Select first card reader
            string firstSCReader = scReaders.FirstOrDefault();

            // Reconnect to card reader, because call GetReaderList() disconnects the connection (ReleaseContext())
            if (!scConnection.EstablishContext())            {
                MessageBox.Show(scConnection.LastErrorString);
                return;
            }

            // Connect to selected reader
            if (!scConnection.ConnectReader(firstSCReader)) {
                MessageBox.Show(scConnection.LastError.ToString() + " " + scConnection.LastErrorString);
                return;
            }

            // Chars (without delimiter) for Application Identifier (AID)
            string scCommand = "315041592E5359532E4444463031";
            string scResponseAID = scConnection.SendAPDU(scCommand);

Hope it helps! ;-)

**Comment by WisnuAnggoro** [comment]
> May I know how to send the APDU commands?

You need to create a text file containing these command:
`RST()` for resetting card (ATR)
`I: {APDU COMMAND}` for sending command
`O: {DATA (If Any)}{SW1SW2}` for expected result from the card (it's optional)
`'` for commenting

The following example is the script for getting UID from Mifare Classic card after getting ATR:
```
RST()
I: FFCA000000
```


And the following is an example to read a transparent EF 6F48 under DF GSM (7F20) on a SIM card
```
' Get ATR
RST()

' PIN (CHV1) is 1234
I: A02000010801020304FFFFFFFF
O: 9F17

' Select DF GSM
I: A0A40000027F20 
O: 9F17

' Select File 6F48
I: A0A40000026F48 
O: 9F10

' Read File 6F48
I: A0B0000010     
```

**Comment by Innosis** [comment]
Noted with thanks.
